# Generated by Django 3.1.7 on 2021-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210401_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='live_image',
            field=models.URLField(default=None),
        ),
    ]
