# Generated by Django 3.1.7 on 2021-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210401_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='live_image',
            field=models.URLField(default='https://live.staticflickr.com/65535/50994357777_353292d837_n.jpg'),
        ),
    ]
