# Generated by Django 3.1.7 on 2021-04-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210402_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=models.TextField(), max_length=255),
        ),
    ]
