# Generated by Django 3.1.7 on 2021-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210402_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_title',
            new_name='subheading',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorised', max_length=30),
        ),
    ]
