# Generated by Django 3.1.7 on 2021-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210402_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subheading',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
