# Generated by Django 3.1.7 on 2021-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210403_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, verbose_name='categories'),
        ),
    ]
