# Generated by Django 3.1.7 on 2021-04-11 18:15

from django.conf import settings
from django.db import migrations, models
from blog.utils import unique_slug_generator


def update_slug(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')

    for instance in Post.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(
                instance, instance.title, instance.slug)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True, null=True, related_name='blog_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(
                blank=True, null=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            update_slug, reverse_code=migrations.RunPython.noop)
    ]
