# Generated by Django 3.1.7 on 2021-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210408_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=100), max_length=255, null=True),
        ),
    ]
