# Generated by Django 3.1.7 on 2021-04-17 17:58

import autoslug.fields
from django.db import migrations
import django.utils.text


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210411_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_populate_from', slugify=django.utils.text.slugify, unique_with=['author', 'date_posted']),
        ),
    ]
