# Generated by Django 3.1.7 on 2021-04-08 17:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210408_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='title', editable=False, populate_from='title', unique_with=('author',)),
        ),
    ]
